### ISSUE TITLE
dune tool version calculation should take dune-configurator into account

### ISSUE THREAD

**Issue by avsm** [tarides/opam-monorepo#101]
The dune-configurator dependencies will constrain the base version of dune allowed (e.g. 2.6.0+), so we need to take that into account for the minimum version of dune recorded in `dune-get`.

e.g. see https://github.com/ocaml/dune/issues/3572

**Comment by tmattio** [comment]
This is the same as https://github.com/tarides/opam-monorepo/issues/263.
It doesn't seem like a good idea to tamper with the solution of the solver depending on the version of Dune installed on the user's system. Instead, if the solver solution requires a more up-to-date version of Dune, we recommend updating Dune to this version.

As for the issue link above, let us know if that's a sensible solution or feel free to re-open.
