### ISSUE TITLE
Semantically equivalent but different "dev-repo" fields lead to build errors

### ISSUE THREAD

**Issue by TheLortex** [tarides/opam-monorepo#118]
The packages `mirage-clock` and `mirage-clock-freestanding` are provided by the same repository but their `dev-repo` fields are different: `git://github.com/mirage/mirage-clock` and `git+https://github.com/mirage/mirage-clock.git`. 
This causes duniverse to download the mirage-clock repo twice under different names, leading to a build error further on are some packages are defined twice.

**Comment by Leonidas-from-XIV** [comment]
Hi @TheLortex, sorry for coming back to this issue so late. I've opened #365 as a workaround to catch this particular case, but for a nice solution it would be best if we could just just unpack one tarball per dependency (so I added the `requires dune change` label), then we wouldn't need to bother with the fragile deduplication.
