### ISSUE TITLE
Relaxing constraints on ocaml version

### ISSUE THREAD

**Issue by emillon** [tarides/opam-monorepo#156]
In certain cases it is desirable not to lock the exact compiler version, but to defer the decision of the exact version to a later stage. In that case, the lock file would only contain something that is equivalent to `>= 4.10 & < 4.11~~`.

**Comment by tmattio** [comment]
This hurts reproducibility, the dependencies should be fixed in the lockfile. Closing this as won't fix, but we can revisit if there's more demand for it.
