### ISSUE TITLE
tracking opam metadata changes in a duniverse

### ISSUE THREAD

**Issue by avsm** [tarides/opam-monorepo#16]
dune 1.10 will hopefully be able to generate opam files from project metadata, which means that we can use a duniverse to create a bunch of opam files in one go (see https://github.com/ocaml/dune/pull/2017)

In [that thread](https://github.com/ocaml/dune/pull/2017#issuecomment-479838279), @jberdine notes: 
> I wonder if any thought has been given to the related problem of how to keep this metadata in sync with changes made to the opam files in the opam-repository? For example, it has happened that missing dependency version constraints were noticed and added directly to opam-repo, and then when I made a new release the added constraint was lost. Other than manually checking each package's opam file in the repo before each release, I don't know of a work flow to preserve such changes.

I'm creating this issue here to track the idea of `duniverse` being able to somehow spot diffs between the opam repository and the local dune file.  This seems pretty tricky at first thought since it's a three way merge: the master branch of the repository may have valid divergences from the released stable package and subsequent fixes in the opam repository.  However, this tool does seem like the right place to figure this out, since `duniverse` bridges both opam and dune together.

**Comment by tmattio** [comment]
If I understand correctly, the goal would be to facilitate the upstreaming of patches from opam-repository to the packages.
If there are features that are missing in opam-monorepo to achieve this, we can work on it, but I'm not sure this is directly in scope for opam-monorepo. Closing for now, but if you think it's still relevant, feel free to re-open with some details on features that would be needed on opam-monorepo.
