### ISSUE TITLE
Feature request: implicitly `--recurse-opam` if there are no top-level opam files

### ISSUE THREAD

**Issue by craigfe** [tarides/opam-monorepo#169]
I'm currently using `opam monorepo lock --recurse-opam` in Tezos to pick up `opam` files that are not in the root directory. It so happens that Tezos has no `opam` files in its root directory, and so not passing `--recurse-opam` will always result in an error:

```
❭ opam monorepo lock
opam-monorepo: Cannot find any packages to vendor.
               Either create some *.opam files in the local repository, or specify them manually via 'duniverse opam <packages>'.
```

Perhaps the `--recurse-opam` flag could be implicit for such projects?

**Comment by tmattio** [comment]
This could cause unwanted behaviour if one expects the lock to only work on the current directory. Being explicit seems like a good default. We can revisit this if there's enough demand for it though.
