### ISSUE TITLE
`opam monorepo lock` fails to parse git repos

### ISSUE THREAD

**Issue by RyanGibb** [tarides/opam-monorepo#334]
```
~/projects/opam-monorepo/_build/default/bin/opam_monorepo.exe lock hello-unix --opam-repositories '[git+https://github.com/ocaml/opam-repositories]'
==> Using 1 locally scanned package as the target.
opam_monorepo.exe: [ERROR] Only non git, local filesystem URLs (file://) are supported at the moment
```

**Comment by Leonidas-from-XIV** [comment]
It's [merged but not released yet](https://github.com/tarides/opam-monorepo/pull/317).

**Comment by RyanGibb** [comment]
Gah I was using the wrong branch! You're absolutely right.

Strangely it prompts for my GitHub credentials (and fails to authenticate with them) when using the most recent branch though.

**Comment by Leonidas-from-XIV** [comment]
That's odd! Are you sure the repo you're trying to use is public? Or try the SSH URI?

**Comment by RyanGibb** [comment]
Ah it's user error again 😭 I keep making the same typo because in `doc/lock.mld` `https://github.com/ocaml/opam-repositories` is used where I think it should be `https://github.com/ocaml/opam-repository`!

**Comment by Leonidas-from-XIV** [comment]
Oh, that's a good catch! If you have a moment, could you submit a PR please?

**Comment by RyanGibb** [comment]
[Done!](https://github.com/tarides/opam-monorepo/pull/335)
