### ISSUE TITLE
opam monorepo lock not applying global opam vars?

### ISSUE THREAD

**Issue by tpetr** [tarides/opam-monorepo#399]
I'm trying to use global opam vars to generate an os-specific lockfile (see https://discuss.ocaml.org/t/opam-monorepo-and-os-specific-dependencies/13302 for context), but it doesnt look like `opam monorepo lock --global-opam-vars` is properly applying the variables. I would expect that something like `opam monorepo lock --global-opam-vars '[[os-distribution,alpine],[os-family,alpine],[os,linux]]'` would propagate the `os-distribution`, `os-family`, and `os` variable overrides to every package it encounters, but that doesn't seem to be the case.

Let me know if there's any additional context I can share to help debug this. Thanks!

**Comment by Leonidas-from-XIV** [comment]
I skimmed the code and I think it only works if you use the explicit_repo solver, not if you use the switch solver which presumably uses the variables that the switch has set.

You can see it in `opam_solve.ml`, only the `Multi_dir_context` uses `opam_env` (which is constructed from `--global-opam-vars`) as `input`, the `Local_opam_context` uses `switch` as `input` and that's just the switch state of OPAM.

**Comment by tpetr** [comment]
Explicitly setting opam repositories did the trick, thanks!
