### ISSUE TITLE
Get a rev-deps duniverse

### ISSUE THREAD

**Issue by NathanReb** [tarides/opam-monorepo#93]
For ppxlib I need to be able to assemble a duniverse with the reverse dependencies of my project so I can test changes that I made, fix the rev-deps locally and upstream those changes.

This kind of workflow would also probably be useful for mirage.

**Comment by NathanReb** [comment]
I'll give this a go while working on ppxlib!

**Comment by avsm** [comment]
Discussed with @NathanReb; a good first cut would be:

- `duniverse pull --revdeps` can look at the shallow reverse dependencies of a root package.
- It solves the transitive dependencies for each of these with an internal call to `duniverse init`
- The resulting packages are pulled.
- dune-get is not modified.

The idea is to do a best effort revdeps which probably wont compile, but this is for advanced users who know what they are doing with opam dependencies.

**Comment by tmattio** [comment]
This is an entirely new workflow. Although it seems very useful, it should probably be implemented outside of opam-monorepo.

One way to achieve that relatively easily would be to list the rev-deps of the package and generate an opam file with them. Then opam monorepo can be used lock and pull the packages.
